# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movideid', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=100)),
                ('release_dte', models.CharField(max_length=11)),
                ('videorelease_dte', models.CharField(max_length=10)),
                ('IMDbURL', models.CharField(max_length=150)),
                ('unknown', models.BooleanField()),
                ('action', models.BooleanField()),
                ('adventure', models.BooleanField()),
                ('animation', models.BooleanField()),
                ('children', models.BooleanField()),
                ('comedy', models.BooleanField()),
                ('crime', models.BooleanField()),
                ('documentary', models.BooleanField()),
                ('drama', models.BooleanField()),
                ('fantasy', models.BooleanField()),
                ('film_Noir', models.BooleanField()),
                ('horror', models.BooleanField()),
                ('musical', models.BooleanField()),
                ('mystery', models.BooleanField()),
                ('romance', models.BooleanField()),
                ('sciFi', models.BooleanField()),
                ('thriller', models.BooleanField()),
                ('war', models.BooleanField()),
                ('western', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rater',
            fields=[
                ('raterid', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('occupation', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('timestmp', models.IntegerField()),
                ('blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_data.Rater')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_data.Movies')),
            ],
        ),
    ]
