# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 20:26
from __future__ import unicode_literals
from movie_data.models import Movies, Rater, Ratings
from django.db import migrations, models
import csv

def add_movies_data(apps, schema_editor):

    with open('u.item', encoding = "latin1") as g:
        reader2 = csv.reader(g, delimiter='|')
        item2 = []
        for row in reader2:
            item2.append(row)

        for row in item2:
            Movies.objects.create(movideid=row[0], movie_title=row[1], release_dte=row[2],
            videorelease_dte=row[3], IMDbURL=row[4], unknown=row[5], action=row[6], adventure=row[7],
            animation=row[8], children=row[9], comedy=row[10], crime=row[11], documentary=row[12],
            drama=row[13], fantasy=row[14], film_Noir=row[15], horror=row[16], musical=row[17],
            mystery=row[18], romance=row[19], sciFi=row[20], thriller=row[21], war=row[22], western=row[23])

def add_rater_data(apps, schema_editor):

    with open('u.user', encoding = "latin1") as h:
        reader3 = csv.reader(h, delimiter='|')

        item3 = []
        for row in reader3:
            item3.append(row)

        for row in item3:
            Rater.objects.create(raterid=row[0], age=row[1], gender=row[2],
            occupation=row[3], zipcode=row[4])

def add_rating_data(apps, schema_editor):


    with open('u.data', encoding = "latin1") as f:
        reader = csv.reader(f, delimiter='\t')
        item = []
        for row in reader:
            item.append(row)

        for row in item:
            Ratings.objects.create(blank=row[0], movie=row[1], rating=row[2], timestmp=row[3])



class Migration(migrations.Migration):

    dependencies = [
        ('movie_data', '0001_initial'),
    ]

    operations = [
        #migrations.RunPython(add_movies_data),
        #migrations.RunPython(add_rater_data),
        #migrations.RunPython(add_rating_data)
    ]
